require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orders_menus", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OrdersMenu. As you add validations to OrdersMenu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrdersMenu.create! valid_attributes
      get orders_menus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      orders_menu = OrdersMenu.create! valid_attributes
      get orders_menu_url(orders_menu)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_orders_menu_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      orders_menu = OrdersMenu.create! valid_attributes
      get edit_orders_menu_url(orders_menu)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrdersMenu" do
        expect {
          post orders_menus_url, params: { orders_menu: valid_attributes }
        }.to change(OrdersMenu, :count).by(1)
      end

      it "redirects to the created orders_menu" do
        post orders_menus_url, params: { orders_menu: valid_attributes }
        expect(response).to redirect_to(orders_menu_url(OrdersMenu.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrdersMenu" do
        expect {
          post orders_menus_url, params: { orders_menu: invalid_attributes }
        }.to change(OrdersMenu, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post orders_menus_url, params: { orders_menu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orders_menu" do
        orders_menu = OrdersMenu.create! valid_attributes
        patch orders_menu_url(orders_menu), params: { orders_menu: new_attributes }
        orders_menu.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the orders_menu" do
        orders_menu = OrdersMenu.create! valid_attributes
        patch orders_menu_url(orders_menu), params: { orders_menu: new_attributes }
        orders_menu.reload
        expect(response).to redirect_to(orders_menu_url(orders_menu))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        orders_menu = OrdersMenu.create! valid_attributes
        patch orders_menu_url(orders_menu), params: { orders_menu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested orders_menu" do
      orders_menu = OrdersMenu.create! valid_attributes
      expect {
        delete orders_menu_url(orders_menu)
      }.to change(OrdersMenu, :count).by(-1)
    end

    it "redirects to the orders_menus list" do
      orders_menu = OrdersMenu.create! valid_attributes
      delete orders_menu_url(orders_menu)
      expect(response).to redirect_to(orders_menus_url)
    end
  end
end
